spring.application.name=order-service

# DB configuration
spring.datasource.url=jdbc:mysql://localhost:1010/order_service_db
spring.datasource.username=root
spring.datasource.password=mysql_root_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Server configuration
server.port=1005

#inv service url
inventory.service.url=http://localhost:1025

# Documentation configuration
springdoc.api-docs.path=/order/api-docs
springdoc.swagger-ui.path=/order/swagger-ui.html