spring.application.name=notification_service
server.port=1200

# Email configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b8e8c8fb2b4a3f
spring.mail.password=5c82eebed09d66