spring.application.name=product-service

# Server port
server.port=1000

# Enable/disable API documentation
springdoc.api-docs.enabled=true

# Database configuration
spring.mongodb.uri=mongodb://root:root@localhost:1060/product_service_db?authSource=admin

# Spring Boot DevTools Configuration
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400

# Documentation configuration
springdoc.api-docs.path=/product/api-docs
springdoc.swagger-ui.path=/product/swagger-ui.html